
// File generated by bin2lvgl, then scaled 360x360 -> 410x410 (centered on a 410x494 canvas)
// developed by fbiego.
// https://github.com/fbiego
// Watchface: red_magic_410 (derived from red_magic "Red Magic" by sernason, via chronos.ke)

#include "red_magic_410.h"

#ifdef ENABLE_FACE_RED_MAGIC_410

lv_obj_t *face_red_magic_410;
lv_obj_t *face_red_magic_410_0_1862;
lv_obj_t *face_red_magic_410_1_1156;
lv_obj_t *face_red_magic_410_2_131494;
lv_obj_t *face_red_magic_410_3_131494;
lv_obj_t *face_red_magic_410_4_131494;
lv_obj_t *face_red_magic_410_5_131494;
lv_obj_t *face_red_magic_410_6_131494;
lv_obj_t *face_red_magic_410_7_131494;
lv_obj_t *face_red_magic_410_8_0;
lv_obj_t *face_red_magic_410_9_0;
lv_obj_t *face_red_magic_410_10_138312;
lv_obj_t *face_red_magic_410_11_138312;
lv_obj_t *face_red_magic_410_12_138312;
lv_obj_t *face_red_magic_410_13_133026;
lv_obj_t *face_red_magic_410_14_136230;
lv_obj_t *face_red_magic_410_15_0;
lv_obj_t *face_red_magic_410_16_138312;
lv_obj_t *face_red_magic_410_17_138312;
lv_obj_t *face_red_magic_410_18_138312;
lv_obj_t *face_red_magic_410_19_138312;
lv_obj_t *face_red_magic_410_21_133464;
lv_obj_t *face_red_magic_410_30_134849;
lv_obj_t *face_red_magic_410_31_134849;
lv_obj_t *face_red_magic_410_32_134849;
lv_obj_t *face_red_magic_410_33_134849;
lv_obj_t *face_red_magic_410_34_139822;
lv_obj_t *face_red_magic_410_43_148537;
lv_obj_t *face_red_magic_410_44_148537;
lv_obj_t *face_red_magic_410_45_148537;
lv_obj_t *face_red_magic_410_46_148537;
lv_obj_t *face_red_magic_410_47_148537;
lv_obj_t *face_red_magic_410_48_151287;
lv_obj_t *face_red_magic_410_49_151287;
lv_obj_t *face_red_magic_410_50_151287;
lv_obj_t *face_red_magic_410_51_151287;
lv_obj_t *face_red_magic_410_52_136123;
lv_obj_t *face_red_magic_410_seconds_hand;


#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif

const lv_img_dsc_t *face_red_magic_410_dial_img_2_131494_group[] = {
	&face_red_magic_410_dial_img_2_131494_0,
	&face_red_magic_410_dial_img_2_131494_1,
	&face_red_magic_410_dial_img_2_131494_2,
	&face_red_magic_410_dial_img_2_131494_3,
	&face_red_magic_410_dial_img_2_131494_4,
	&face_red_magic_410_dial_img_2_131494_5,
	&face_red_magic_410_dial_img_2_131494_6,
	&face_red_magic_410_dial_img_2_131494_7,
	&face_red_magic_410_dial_img_2_131494_8,
	&face_red_magic_410_dial_img_2_131494_9,
};
const lv_img_dsc_t *face_red_magic_410_dial_img_10_138312_group[] = {
	&face_red_magic_410_dial_img_10_138312_0,
	&face_red_magic_410_dial_img_10_138312_1,
	&face_red_magic_410_dial_img_10_138312_2,
	&face_red_magic_410_dial_img_10_138312_3,
	&face_red_magic_410_dial_img_10_138312_4,
	&face_red_magic_410_dial_img_10_138312_5,
	&face_red_magic_410_dial_img_10_138312_6,
	&face_red_magic_410_dial_img_10_138312_7,
	&face_red_magic_410_dial_img_10_138312_8,
	&face_red_magic_410_dial_img_10_138312_9,
};
const lv_img_dsc_t *face_red_magic_410_dial_img_weather[] = {
	&face_red_magic_410_dial_img_21_133464_0,
	&face_red_magic_410_dial_img_22_149959_0,
	&face_red_magic_410_dial_img_23_147317_0,
	&face_red_magic_410_dial_img_24_143164_0,
	&face_red_magic_410_dial_img_25_141878_0,
	&face_red_magic_410_dial_img_26_144432_0,
	&face_red_magic_410_dial_img_27_156001_0,
	&face_red_magic_410_dial_img_28_136666_0,
	&face_red_magic_410_dial_img_29_140520_0,
};
const lv_img_dsc_t *face_red_magic_410_dial_img_30_134849_group[] = {
	&face_red_magic_410_dial_img_30_134849_0,
	&face_red_magic_410_dial_img_30_134849_1,
	&face_red_magic_410_dial_img_30_134849_2,
	&face_red_magic_410_dial_img_30_134849_3,
	&face_red_magic_410_dial_img_30_134849_4,
	&face_red_magic_410_dial_img_30_134849_5,
	&face_red_magic_410_dial_img_30_134849_6,
	&face_red_magic_410_dial_img_30_134849_7,
	&face_red_magic_410_dial_img_30_134849_8,
	&face_red_magic_410_dial_img_30_134849_9,
};
const lv_img_dsc_t *face_red_magic_410_dial_img_43_148537_group[] = {
	&face_red_magic_410_dial_img_43_148537_0,
	&face_red_magic_410_dial_img_43_148537_1,
	&face_red_magic_410_dial_img_43_148537_2,
	&face_red_magic_410_dial_img_43_148537_3,
	&face_red_magic_410_dial_img_43_148537_4,
	&face_red_magic_410_dial_img_43_148537_5,
	&face_red_magic_410_dial_img_43_148537_6,
	&face_red_magic_410_dial_img_43_148537_7,
	&face_red_magic_410_dial_img_43_148537_8,
	&face_red_magic_410_dial_img_43_148537_9,
};
const lv_img_dsc_t *face_red_magic_410_dial_img_48_151287_group[] = {
	&face_red_magic_410_dial_img_48_151287_0,
	&face_red_magic_410_dial_img_48_151287_1,
	&face_red_magic_410_dial_img_48_151287_2,
	&face_red_magic_410_dial_img_48_151287_3,
	&face_red_magic_410_dial_img_48_151287_4,
	&face_red_magic_410_dial_img_48_151287_5,
	&face_red_magic_410_dial_img_48_151287_6,
	&face_red_magic_410_dial_img_48_151287_7,
	&face_red_magic_410_dial_img_48_151287_8,
	&face_red_magic_410_dial_img_48_151287_9,
};




#endif

void init_face_red_magic_410(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **, lv_obj_t **)){
#ifdef ENABLE_FACE_RED_MAGIC_410
    face_red_magic_410 = lv_obj_create(NULL);
    lv_obj_clear_flag(face_red_magic_410, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_red_magic_410, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_red_magic_410, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_red_magic_410, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_red_magic_410, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_red_magic_410, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_red_magic_410, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_red_magic_410, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_add_event_cb(face_red_magic_410, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_red_magic_410_0_1862 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_0_1862, &face_red_magic_410_dial_img_0_1862_0);
    lv_obj_set_width(face_red_magic_410_0_1862, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_0_1862, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_0_1862, 0);
    lv_obj_set_y(face_red_magic_410_0_1862, 42);
    lv_obj_add_flag(face_red_magic_410_0_1862, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_0_1862, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_1_1156 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_1_1156, &face_red_magic_410_dial_img_1_1156_0);
    lv_obj_set_width(face_red_magic_410_1_1156, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_1_1156, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_1_1156, 330);
    lv_obj_set_y(face_red_magic_410_1_1156, 168);
    lv_obj_add_flag(face_red_magic_410_1_1156, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_1_1156, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_2_131494 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_2_131494, &face_red_magic_410_dial_img_2_131494_0);
    lv_obj_set_width(face_red_magic_410_2_131494, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_2_131494, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_2_131494, 318);
    lv_obj_set_y(face_red_magic_410_2_131494, 168);
    lv_obj_add_flag(face_red_magic_410_2_131494, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_2_131494, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_3_131494 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_3_131494, &face_red_magic_410_dial_img_2_131494_0);
    lv_obj_set_width(face_red_magic_410_3_131494, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_3_131494, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_3_131494, 305);
    lv_obj_set_y(face_red_magic_410_3_131494, 168);
    lv_obj_add_flag(face_red_magic_410_3_131494, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_3_131494, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_4_131494 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_4_131494, &face_red_magic_410_dial_img_2_131494_0);
    lv_obj_set_width(face_red_magic_410_4_131494, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_4_131494, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_4_131494, 293);
    lv_obj_set_y(face_red_magic_410_4_131494, 168);
    lv_obj_add_flag(face_red_magic_410_4_131494, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_4_131494, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_5_131494 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_5_131494, &face_red_magic_410_dial_img_2_131494_0);
    lv_obj_set_width(face_red_magic_410_5_131494, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_5_131494, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_5_131494, 320);
    lv_obj_set_y(face_red_magic_410_5_131494, 311);
    lv_obj_add_flag(face_red_magic_410_5_131494, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_5_131494, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_6_131494 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_6_131494, &face_red_magic_410_dial_img_2_131494_0);
    lv_obj_set_width(face_red_magic_410_6_131494, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_6_131494, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_6_131494, 308);
    lv_obj_set_y(face_red_magic_410_6_131494, 311);
    lv_obj_add_flag(face_red_magic_410_6_131494, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_6_131494, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_7_131494 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_7_131494, &face_red_magic_410_dial_img_2_131494_0);
    lv_obj_set_width(face_red_magic_410_7_131494, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_7_131494, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_7_131494, 295);
    lv_obj_set_y(face_red_magic_410_7_131494, 311);
    lv_obj_add_flag(face_red_magic_410_7_131494, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_7_131494, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_8_0 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_8_0, &face_red_magic_410_dial_img_8_0_0);
    lv_obj_set_width(face_red_magic_410_8_0, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_8_0, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_8_0, 80);
    lv_obj_set_y(face_red_magic_410_8_0, 167);
    lv_obj_add_flag(face_red_magic_410_8_0, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_8_0, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_9_0 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_9_0, &face_red_magic_410_dial_img_8_0_0);
    lv_obj_set_width(face_red_magic_410_9_0, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_9_0, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_9_0, 68);
    lv_obj_set_y(face_red_magic_410_9_0, 167);
    lv_obj_add_flag(face_red_magic_410_9_0, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_9_0, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_10_138312 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_10_138312, &face_red_magic_410_dial_img_10_138312_0);
    lv_obj_set_width(face_red_magic_410_10_138312, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_10_138312, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_10_138312, 80);
    lv_obj_set_y(face_red_magic_410_10_138312, 159);
    lv_obj_add_flag(face_red_magic_410_10_138312, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_10_138312, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_11_138312 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_11_138312, &face_red_magic_410_dial_img_10_138312_0);
    lv_obj_set_width(face_red_magic_410_11_138312, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_11_138312, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_11_138312, 68);
    lv_obj_set_y(face_red_magic_410_11_138312, 159);
    lv_obj_add_flag(face_red_magic_410_11_138312, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_11_138312, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_12_138312 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_12_138312, &face_red_magic_410_dial_img_10_138312_0);
    lv_obj_set_width(face_red_magic_410_12_138312, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_12_138312, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_12_138312, 57);
    lv_obj_set_y(face_red_magic_410_12_138312, 159);
    lv_obj_add_flag(face_red_magic_410_12_138312, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_12_138312, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_13_133026 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_13_133026, &face_red_magic_410_dial_img_13_133026_0);
    lv_obj_set_width(face_red_magic_410_13_133026, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_13_133026, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_13_133026, 92);
    lv_obj_set_y(face_red_magic_410_13_133026, 159);
    lv_obj_add_flag(face_red_magic_410_13_133026, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_13_133026, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_14_136230 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_14_136230, &face_red_magic_410_dial_img_14_136230_0);
    lv_obj_set_width(face_red_magic_410_14_136230, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_14_136230, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_14_136230, 92);
    lv_obj_set_y(face_red_magic_410_14_136230, 159);
    lv_obj_add_flag(face_red_magic_410_14_136230, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_14_136230, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_15_0 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_15_0, &face_red_magic_410_dial_img_8_0_0);
    lv_obj_set_width(face_red_magic_410_15_0, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_15_0, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_15_0, 57);
    lv_obj_set_y(face_red_magic_410_15_0, 167);
    lv_obj_add_flag(face_red_magic_410_15_0, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_15_0, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_16_138312 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_16_138312, &face_red_magic_410_dial_img_10_138312_0);
    lv_obj_set_width(face_red_magic_410_16_138312, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_16_138312, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_16_138312, 271);
    lv_obj_set_y(face_red_magic_410_16_138312, 131);
    lv_obj_add_flag(face_red_magic_410_16_138312, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_16_138312, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_17_138312 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_17_138312, &face_red_magic_410_dial_img_10_138312_0);
    lv_obj_set_width(face_red_magic_410_17_138312, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_17_138312, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_17_138312, 260);
    lv_obj_set_y(face_red_magic_410_17_138312, 131);
    lv_obj_add_flag(face_red_magic_410_17_138312, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_17_138312, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_18_138312 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_18_138312, &face_red_magic_410_dial_img_10_138312_0);
    lv_obj_set_width(face_red_magic_410_18_138312, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_18_138312, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_18_138312, 248);
    lv_obj_set_y(face_red_magic_410_18_138312, 131);
    lv_obj_add_flag(face_red_magic_410_18_138312, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_18_138312, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_19_138312 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_19_138312, &face_red_magic_410_dial_img_10_138312_0);
    lv_obj_set_width(face_red_magic_410_19_138312, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_19_138312, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_19_138312, 237);
    lv_obj_set_y(face_red_magic_410_19_138312, 131);
    lv_obj_add_flag(face_red_magic_410_19_138312, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_19_138312, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_21_133464 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_21_133464, &face_red_magic_410_dial_img_21_133464_0);
    lv_obj_set_width(face_red_magic_410_21_133464, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_21_133464, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_21_133464, 65);
    lv_obj_set_y(face_red_magic_410_21_133464, 106);
    lv_obj_add_flag(face_red_magic_410_21_133464, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_21_133464, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_30_134849 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_30_134849, &face_red_magic_410_dial_img_30_134849_0);
    lv_obj_set_width(face_red_magic_410_30_134849, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_30_134849, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_30_134849, 358);
    lv_obj_set_y(face_red_magic_410_30_134849, 216);
    lv_obj_add_flag(face_red_magic_410_30_134849, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_30_134849, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_31_134849 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_31_134849, &face_red_magic_410_dial_img_30_134849_0);
    lv_obj_set_width(face_red_magic_410_31_134849, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_31_134849, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_31_134849, 346);
    lv_obj_set_y(face_red_magic_410_31_134849, 216);
    lv_obj_add_flag(face_red_magic_410_31_134849, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_31_134849, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_32_134849 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_32_134849, &face_red_magic_410_dial_img_30_134849_0);
    lv_obj_set_width(face_red_magic_410_32_134849, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_32_134849, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_32_134849, 319);
    lv_obj_set_y(face_red_magic_410_32_134849, 216);
    lv_obj_add_flag(face_red_magic_410_32_134849, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_32_134849, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_33_134849 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_33_134849, &face_red_magic_410_dial_img_30_134849_0);
    lv_obj_set_width(face_red_magic_410_33_134849, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_33_134849, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_33_134849, 308);
    lv_obj_set_y(face_red_magic_410_33_134849, 216);
    lv_obj_add_flag(face_red_magic_410_33_134849, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_33_134849, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_34_139822 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_34_139822, &face_red_magic_410_dial_img_34_139822_0);
    lv_obj_set_width(face_red_magic_410_34_139822, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_34_139822, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_34_139822, 335);
    lv_obj_set_y(face_red_magic_410_34_139822, 222);
    lv_obj_add_flag(face_red_magic_410_34_139822, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_34_139822, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_43_148537 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_43_148537, &face_red_magic_410_dial_img_43_148537_0);
    lv_obj_set_width(face_red_magic_410_43_148537, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_43_148537, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_43_148537, 286);
    lv_obj_set_y(face_red_magic_410_43_148537, 351);
    lv_obj_add_flag(face_red_magic_410_43_148537, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_43_148537, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_44_148537 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_44_148537, &face_red_magic_410_dial_img_43_148537_0);
    lv_obj_set_width(face_red_magic_410_44_148537, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_44_148537, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_44_148537, 274);
    lv_obj_set_y(face_red_magic_410_44_148537, 351);
    lv_obj_add_flag(face_red_magic_410_44_148537, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_44_148537, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_45_148537 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_45_148537, &face_red_magic_410_dial_img_43_148537_0);
    lv_obj_set_width(face_red_magic_410_45_148537, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_45_148537, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_45_148537, 263);
    lv_obj_set_y(face_red_magic_410_45_148537, 351);
    lv_obj_add_flag(face_red_magic_410_45_148537, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_45_148537, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_46_148537 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_46_148537, &face_red_magic_410_dial_img_43_148537_0);
    lv_obj_set_width(face_red_magic_410_46_148537, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_46_148537, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_46_148537, 252);
    lv_obj_set_y(face_red_magic_410_46_148537, 351);
    lv_obj_add_flag(face_red_magic_410_46_148537, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_46_148537, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_47_148537 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_47_148537, &face_red_magic_410_dial_img_43_148537_0);
    lv_obj_set_width(face_red_magic_410_47_148537, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_47_148537, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_47_148537, 240);
    lv_obj_set_y(face_red_magic_410_47_148537, 351);
    lv_obj_add_flag(face_red_magic_410_47_148537, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_47_148537, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_48_151287 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_48_151287, &face_red_magic_410_dial_img_48_151287_0);
    lv_obj_set_width(face_red_magic_410_48_151287, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_48_151287, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_48_151287, 310);
    lv_obj_set_y(face_red_magic_410_48_151287, 238);
    lv_obj_add_flag(face_red_magic_410_48_151287, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_48_151287, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_49_151287 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_49_151287, &face_red_magic_410_dial_img_48_151287_0);
    lv_obj_set_width(face_red_magic_410_49_151287, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_49_151287, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_49_151287, 286);
    lv_obj_set_y(face_red_magic_410_49_151287, 238);
    lv_obj_add_flag(face_red_magic_410_49_151287, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_49_151287, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_50_151287 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_50_151287, &face_red_magic_410_dial_img_48_151287_0);
    lv_obj_set_width(face_red_magic_410_50_151287, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_50_151287, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_50_151287, 369);
    lv_obj_set_y(face_red_magic_410_50_151287, 238);
    lv_obj_add_flag(face_red_magic_410_50_151287, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_50_151287, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_51_151287 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_51_151287, &face_red_magic_410_dial_img_48_151287_0);
    lv_obj_set_width(face_red_magic_410_51_151287, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_51_151287, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_51_151287, 345);
    lv_obj_set_y(face_red_magic_410_51_151287, 238);
    lv_obj_add_flag(face_red_magic_410_51_151287, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_51_151287, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_410_52_136123 = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_52_136123, &face_red_magic_410_dial_img_52_136123_0);
    lv_obj_set_width(face_red_magic_410_52_136123, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_52_136123, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_410_52_136123, 333);
    lv_obj_set_y(face_red_magic_410_52_136123, 246);
    lv_obj_add_flag(face_red_magic_410_52_136123, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_52_136123, LV_OBJ_FLAG_SCROLLABLE );

    // Hand-authored seconds hand: the original bin has 3 "Analog x5" elements pivoting on
    // this exact point (180,180 in the source 360x360 space -> 205,247 here) that bin2lvgl
    // can't decode, so this is a synthesized replacement rather than a recovered asset.
    // Rotates once per minute (6 deg/sec = 60 tenths-of-a-degree/sec, LVGL9 rotation units).
    face_red_magic_410_seconds_hand = lv_img_create(face_red_magic_410);
    lv_img_set_src(face_red_magic_410_seconds_hand, &face_red_magic_410_dial_img_seconds_hand);
    lv_obj_set_width(face_red_magic_410_seconds_hand, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_410_seconds_hand, LV_SIZE_CONTENT);
    // Position derived from directly measuring the background art's reticle pixel centroid
    // (207,246 in canvas space) - a close-up photo confirmed the pivot really was down-left
    // of the true center (validating that direction), but photo-based distance measurement
    // through a tiny ~14px reference ring was too noisy to trust for magnitude, so going with
    // the precise asset-derived figure instead: pivot = canvas(207,246), i.e.
    // object_x = 207-4, object_y = 246-78.
    lv_obj_set_x(face_red_magic_410_seconds_hand, 203);
    lv_obj_set_y(face_red_magic_410_seconds_hand, 168);
    lv_obj_add_flag(face_red_magic_410_seconds_hand, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_410_seconds_hand, LV_OBJ_FLAG_SCROLLABLE );
    lv_image_set_pivot(face_red_magic_410_seconds_hand, 4, 78);


    callback("red magic", &face_red_magic_410_dial_img_preview_0, &face_red_magic_410, NULL);

#endif
}

void update_time_red_magic_410(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
#ifdef ENABLE_FACE_RED_MAGIC_410
    if (!face_red_magic_410)
    {
        return;
    }
	lv_img_set_src(face_red_magic_410_30_134849, face_red_magic_410_dial_img_30_134849_group[(month / 1) % 10]);
	lv_img_set_src(face_red_magic_410_31_134849, face_red_magic_410_dial_img_30_134849_group[(month / 10) % 10]);
	lv_img_set_src(face_red_magic_410_32_134849, face_red_magic_410_dial_img_30_134849_group[(day / 1) % 10]);
	lv_img_set_src(face_red_magic_410_33_134849, face_red_magic_410_dial_img_30_134849_group[(day / 10) % 10]);
	lv_img_set_src(face_red_magic_410_48_151287, face_red_magic_410_dial_img_48_151287_group[(hour / 1) % 10]);
	lv_img_set_src(face_red_magic_410_49_151287, face_red_magic_410_dial_img_48_151287_group[(hour / 10) % 10]);
	lv_img_set_src(face_red_magic_410_50_151287, face_red_magic_410_dial_img_48_151287_group[(minute / 1) % 10]);
	lv_img_set_src(face_red_magic_410_51_151287, face_red_magic_410_dial_img_48_151287_group[(minute / 10) % 10]);
	lv_image_set_rotation(face_red_magic_410_seconds_hand, second * 60);

#endif
}

void update_weather_red_magic_410(int temp, int icon)
{
#ifdef ENABLE_FACE_RED_MAGIC_410
    if (!face_red_magic_410)
    {
        return;
    }
	lv_img_set_src(face_red_magic_410_21_133464, face_red_magic_410_dial_img_weather[icon % 8]);

	// watch.getWeatherAt(0).temp is already Celsius, unconverted - confirmed against the
	// working 1167 face's update_weather_1167(), which uses raw temp directly.
	// Digit positions: items.txt has these 3 objects at x=70/60/50 - cross-checked against
	// this same file's working update_activity_red_magic_410() kcal digits (x=238/228/218/208
	// mapped to ones/tens/hundreds/thousands), higher x = lower place value. So x=70 (highest)
	// is ones, x=50 (lowest) is hundreds.
	int mag = temp < 0 ? -temp : temp;
	lv_img_set_src(face_red_magic_410_10_138312, face_red_magic_410_dial_img_10_138312_group[(mag / 1) % 10]);
	lv_img_set_src(face_red_magic_410_11_138312, face_red_magic_410_dial_img_10_138312_group[(mag / 10) % 10]);
	lv_img_set_src(face_red_magic_410_12_138312, face_red_magic_410_dial_img_10_138312_group[(mag / 100) % 10]);
	if (mag < 100)
	{
		// Belt-and-suspenders hide: HIDDEN flag alone left a speckled artifact on-device
		// (root cause not fully confirmed without a photo - possibly a stale/partial
		// invalidation on this particular object) so also physically move it off-canvas.
		// Digit content is always still set above regardless, ready to reappear at x=57
		// on the rare/impossible-for-Celsius chance this position is ever needed.
		lv_obj_add_flag(face_red_magic_410_12_138312, LV_OBJ_FLAG_HIDDEN);
		lv_obj_set_x(face_red_magic_410_12_138312, -100);
	} else {
		lv_obj_clear_flag(face_red_magic_410_12_138312, LV_OBJ_FLAG_HIDDEN);
		lv_obj_set_x(face_red_magic_410_12_138312, 57);
	}
	// face_red_magic_410_15_0 is a genuine minus-sign glyph (items.txt rows 8/9/15, type
	// 0xFA "Weather no+label" - fully supported by bin2lvgl, not one of the skipped Analog
	// elements) sitting directly under the hundreds-digit slot at the same x - it was always
	// being drawn, just permanently covered by that digit until the fix above started hiding
	// it, which is what exposed it as a stray dash on-device. Same belt-and-suspenders
	// treatment: shown only for genuinely negative temps, moved off-canvas otherwise.
	if (temp < 0)
	{
		lv_obj_clear_flag(face_red_magic_410_15_0, LV_OBJ_FLAG_HIDDEN);
		lv_obj_set_x(face_red_magic_410_15_0, 57);
	} else {
		lv_obj_add_flag(face_red_magic_410_15_0, LV_OBJ_FLAG_HIDDEN);
		lv_obj_set_x(face_red_magic_410_15_0, -100);
	}
	// face_red_magic_410_13_133026 = "°C" glyph, face_red_magic_410_14_136230 = "°F" glyph
	// (confirmed by decoding both assets directly - bin2lvgl gave no label metadata).
	lv_obj_clear_flag(face_red_magic_410_13_133026, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(face_red_magic_410_14_136230, LV_OBJ_FLAG_HIDDEN);

#endif
}

void update_status_red_magic_410(int battery, bool connection){
#ifdef ENABLE_FACE_RED_MAGIC_410
    if (!face_red_magic_410)
    {
        return;
    }
	lv_img_set_src(face_red_magic_410_2_131494, face_red_magic_410_dial_img_2_131494_group[(battery / 1) % 10]);
	lv_img_set_src(face_red_magic_410_3_131494, face_red_magic_410_dial_img_2_131494_group[(battery / 10) % 10]);
	lv_img_set_src(face_red_magic_410_4_131494, face_red_magic_410_dial_img_2_131494_group[(battery / 100) % 10]);
	if (battery < 100)
	{
		lv_obj_add_flag(face_red_magic_410_4_131494, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_red_magic_410_4_131494, LV_OBJ_FLAG_HIDDEN);
	}

#endif
}

void update_activity_red_magic_410(int steps, int distance, int kcal)
{
#ifdef ENABLE_FACE_RED_MAGIC_410
    if (!face_red_magic_410)
    {
        return;
    }
	lv_img_set_src(face_red_magic_410_16_138312, face_red_magic_410_dial_img_10_138312_group[(kcal / 1) % 10]);
	lv_img_set_src(face_red_magic_410_17_138312, face_red_magic_410_dial_img_10_138312_group[(kcal / 10) % 10]);
	lv_img_set_src(face_red_magic_410_18_138312, face_red_magic_410_dial_img_10_138312_group[(kcal / 100) % 10]);
	lv_img_set_src(face_red_magic_410_19_138312, face_red_magic_410_dial_img_10_138312_group[(kcal / 1000) % 10]);
	lv_img_set_src(face_red_magic_410_43_148537, face_red_magic_410_dial_img_43_148537_group[(steps / 1) % 10]);
	lv_img_set_src(face_red_magic_410_44_148537, face_red_magic_410_dial_img_43_148537_group[(steps / 10) % 10]);
	lv_img_set_src(face_red_magic_410_45_148537, face_red_magic_410_dial_img_43_148537_group[(steps / 100) % 10]);
	lv_img_set_src(face_red_magic_410_46_148537, face_red_magic_410_dial_img_43_148537_group[(steps / 1000) % 10]);
	lv_img_set_src(face_red_magic_410_47_148537, face_red_magic_410_dial_img_43_148537_group[(steps / 10000) % 10]);

#endif
}

void update_health_red_magic_410(int bpm, int oxygen)
{
#ifdef ENABLE_FACE_RED_MAGIC_410
    if (!face_red_magic_410)
    {
        return;
    }
	lv_img_set_src(face_red_magic_410_5_131494, face_red_magic_410_dial_img_2_131494_group[(bpm / 1) % 10]);
	lv_img_set_src(face_red_magic_410_6_131494, face_red_magic_410_dial_img_2_131494_group[(bpm / 10) % 10]);
	lv_img_set_src(face_red_magic_410_7_131494, face_red_magic_410_dial_img_2_131494_group[(bpm / 100) % 10]);

#endif
}

void update_all_red_magic_410(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_RED_MAGIC_410
    update_time_red_magic_410(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_red_magic_410(temp, icon);
    update_status_red_magic_410(battery, connection);
    update_activity_red_magic_410(steps, distance, kcal);
    update_health_red_magic_410(bpm, oxygen);
#endif
}

void update_check_red_magic_410(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_RED_MAGIC_410
    if (root != face_red_magic_410)
    {
        return;
    }
    update_time_red_magic_410(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_red_magic_410(temp, icon);
    update_status_red_magic_410(battery, connection);
    update_activity_red_magic_410(steps, distance, kcal);
    update_health_red_magic_410(bpm, oxygen);
#endif
}


