
// File generated by bin2lvgl, then scaled 360x360 -> 410x410 (centered on a 410x494 canvas)
// developed by fbiego.
// https://github.com/fbiego
// Watchface: red_magic_410 (derived from red_magic "Red Magic" by sernason, via chronos.ke)

#ifndef _FACE_RED_MAGIC_410_H
#define _FACE_RED_MAGIC_410_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"
#include "app_hal.h"

//#define ENABLE_FACE_RED_MAGIC_410 // (red magic) uncomment to enable or define it elsewhere

#ifdef ENABLE_FACE_RED_MAGIC_410
    extern lv_obj_t *face_red_magic_410;
	extern lv_obj_t *face_red_magic_410_0_1862;
	extern lv_obj_t *face_red_magic_410_1_1156;
	extern lv_obj_t *face_red_magic_410_2_131494;
	extern lv_obj_t *face_red_magic_410_3_131494;
	extern lv_obj_t *face_red_magic_410_4_131494;
	extern lv_obj_t *face_red_magic_410_5_131494;
	extern lv_obj_t *face_red_magic_410_6_131494;
	extern lv_obj_t *face_red_magic_410_7_131494;
	extern lv_obj_t *face_red_magic_410_8_0;
	extern lv_obj_t *face_red_magic_410_9_0;
	extern lv_obj_t *face_red_magic_410_10_138312;
	extern lv_obj_t *face_red_magic_410_11_138312;
	extern lv_obj_t *face_red_magic_410_12_138312;
	extern lv_obj_t *face_red_magic_410_13_133026;
	extern lv_obj_t *face_red_magic_410_14_136230;
	extern lv_obj_t *face_red_magic_410_15_0;
	extern lv_obj_t *face_red_magic_410_16_138312;
	extern lv_obj_t *face_red_magic_410_17_138312;
	extern lv_obj_t *face_red_magic_410_18_138312;
	extern lv_obj_t *face_red_magic_410_19_138312;
	extern lv_obj_t *face_red_magic_410_21_133464;
	extern lv_obj_t *face_red_magic_410_30_134849;
	extern lv_obj_t *face_red_magic_410_31_134849;
	extern lv_obj_t *face_red_magic_410_32_134849;
	extern lv_obj_t *face_red_magic_410_33_134849;
	extern lv_obj_t *face_red_magic_410_34_139822;
	extern lv_obj_t *face_red_magic_410_43_148537;
	extern lv_obj_t *face_red_magic_410_44_148537;
	extern lv_obj_t *face_red_magic_410_45_148537;
	extern lv_obj_t *face_red_magic_410_46_148537;
	extern lv_obj_t *face_red_magic_410_47_148537;
	extern lv_obj_t *face_red_magic_410_48_151287;
	extern lv_obj_t *face_red_magic_410_49_151287;
	extern lv_obj_t *face_red_magic_410_50_151287;
	extern lv_obj_t *face_red_magic_410_51_151287;
	extern lv_obj_t *face_red_magic_410_52_136123;
	extern lv_obj_t *face_red_magic_410_seconds_hand;


	LV_IMG_DECLARE(face_red_magic_410_dial_img_seconds_hand);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_0_1862_0);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_1_1156_0);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_2_131494_0);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_2_131494_1);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_2_131494_2);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_2_131494_3);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_2_131494_4);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_2_131494_5);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_2_131494_6);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_2_131494_7);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_2_131494_8);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_2_131494_9);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_8_0_0);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_10_138312_0);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_10_138312_1);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_10_138312_2);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_10_138312_3);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_10_138312_4);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_10_138312_5);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_10_138312_6);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_10_138312_7);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_10_138312_8);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_10_138312_9);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_13_133026_0);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_14_136230_0);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_21_133464_0);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_22_149959_0);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_23_147317_0);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_24_143164_0);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_25_141878_0);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_26_144432_0);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_27_156001_0);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_28_136666_0);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_29_140520_0);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_30_134849_0);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_30_134849_1);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_30_134849_2);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_30_134849_3);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_30_134849_4);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_30_134849_5);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_30_134849_6);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_30_134849_7);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_30_134849_8);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_30_134849_9);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_34_139822_0);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_39_137944_0);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_43_148537_0);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_43_148537_1);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_43_148537_2);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_43_148537_3);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_43_148537_4);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_43_148537_5);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_43_148537_6);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_43_148537_7);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_43_148537_8);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_43_148537_9);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_48_151287_0);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_48_151287_1);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_48_151287_2);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_48_151287_3);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_48_151287_4);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_48_151287_5);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_48_151287_6);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_48_151287_7);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_48_151287_8);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_48_151287_9);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_52_136123_0);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_preview_0);
	LV_IMG_DECLARE(face_red_magic_410_dial_img_preview_0);


#endif
    void onFaceEvent(lv_event_t * e);

    void init_face_red_magic_410(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **, lv_obj_t **));
    void update_time_red_magic_410(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday);
    void update_weather_red_magic_410(int temp, int icon);
    void update_status_red_magic_410(int battery, bool connection);
    void update_activity_red_magic_410(int steps, int distance, int kcal);
    void update_health_red_magic_410(int bpm, int oxygen);
    void update_all_red_magic_410(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);
    void update_check_red_magic_410(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
                int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen);


#ifdef __cplusplus
}
#endif

#endif
