
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: RED_MAGIC

#include "red_magic.h"

#ifdef ENABLE_FACE_RED_MAGIC

lv_obj_t *face_red_magic;
lv_obj_t *face_red_magic_0_1862;
lv_obj_t *face_red_magic_1_1156;
lv_obj_t *face_red_magic_2_131494;
lv_obj_t *face_red_magic_3_131494;
lv_obj_t *face_red_magic_4_131494;
lv_obj_t *face_red_magic_5_131494;
lv_obj_t *face_red_magic_6_131494;
lv_obj_t *face_red_magic_7_131494;
lv_obj_t *face_red_magic_8_0;
lv_obj_t *face_red_magic_9_0;
lv_obj_t *face_red_magic_10_138312;
lv_obj_t *face_red_magic_11_138312;
lv_obj_t *face_red_magic_12_138312;
lv_obj_t *face_red_magic_13_133026;
lv_obj_t *face_red_magic_14_136230;
lv_obj_t *face_red_magic_15_0;
lv_obj_t *face_red_magic_16_138312;
lv_obj_t *face_red_magic_17_138312;
lv_obj_t *face_red_magic_18_138312;
lv_obj_t *face_red_magic_19_138312;
lv_obj_t *face_red_magic_21_133464;
lv_obj_t *face_red_magic_30_134849;
lv_obj_t *face_red_magic_31_134849;
lv_obj_t *face_red_magic_32_134849;
lv_obj_t *face_red_magic_33_134849;
lv_obj_t *face_red_magic_34_139822;
lv_obj_t *face_red_magic_43_148537;
lv_obj_t *face_red_magic_44_148537;
lv_obj_t *face_red_magic_45_148537;
lv_obj_t *face_red_magic_46_148537;
lv_obj_t *face_red_magic_47_148537;
lv_obj_t *face_red_magic_48_151287;
lv_obj_t *face_red_magic_49_151287;
lv_obj_t *face_red_magic_50_151287;
lv_obj_t *face_red_magic_51_151287;
lv_obj_t *face_red_magic_52_136123;


#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit for watchfaces"
#endif

const lv_img_dsc_t *face_red_magic_dial_img_2_131494_group[] = {
	&face_red_magic_dial_img_2_131494_0,
	&face_red_magic_dial_img_2_131494_1,
	&face_red_magic_dial_img_2_131494_2,
	&face_red_magic_dial_img_2_131494_3,
	&face_red_magic_dial_img_2_131494_4,
	&face_red_magic_dial_img_2_131494_5,
	&face_red_magic_dial_img_2_131494_6,
	&face_red_magic_dial_img_2_131494_7,
	&face_red_magic_dial_img_2_131494_8,
	&face_red_magic_dial_img_2_131494_9,
};
const lv_img_dsc_t *face_red_magic_dial_img_10_138312_group[] = {
	&face_red_magic_dial_img_10_138312_0,
	&face_red_magic_dial_img_10_138312_1,
	&face_red_magic_dial_img_10_138312_2,
	&face_red_magic_dial_img_10_138312_3,
	&face_red_magic_dial_img_10_138312_4,
	&face_red_magic_dial_img_10_138312_5,
	&face_red_magic_dial_img_10_138312_6,
	&face_red_magic_dial_img_10_138312_7,
	&face_red_magic_dial_img_10_138312_8,
	&face_red_magic_dial_img_10_138312_9,
};
const lv_img_dsc_t *face_red_magic_dial_img_weather[] = {
	&face_red_magic_dial_img_21_133464_0,
	&face_red_magic_dial_img_22_149959_0,
	&face_red_magic_dial_img_23_147317_0,
	&face_red_magic_dial_img_24_143164_0,
	&face_red_magic_dial_img_25_141878_0,
	&face_red_magic_dial_img_26_144432_0,
	&face_red_magic_dial_img_27_156001_0,
	&face_red_magic_dial_img_28_136666_0,
	&face_red_magic_dial_img_29_140520_0,
};
const lv_img_dsc_t *face_red_magic_dial_img_30_134849_group[] = {
	&face_red_magic_dial_img_30_134849_0,
	&face_red_magic_dial_img_30_134849_1,
	&face_red_magic_dial_img_30_134849_2,
	&face_red_magic_dial_img_30_134849_3,
	&face_red_magic_dial_img_30_134849_4,
	&face_red_magic_dial_img_30_134849_5,
	&face_red_magic_dial_img_30_134849_6,
	&face_red_magic_dial_img_30_134849_7,
	&face_red_magic_dial_img_30_134849_8,
	&face_red_magic_dial_img_30_134849_9,
};
const lv_img_dsc_t *face_red_magic_dial_img_43_148537_group[] = {
	&face_red_magic_dial_img_43_148537_0,
	&face_red_magic_dial_img_43_148537_1,
	&face_red_magic_dial_img_43_148537_2,
	&face_red_magic_dial_img_43_148537_3,
	&face_red_magic_dial_img_43_148537_4,
	&face_red_magic_dial_img_43_148537_5,
	&face_red_magic_dial_img_43_148537_6,
	&face_red_magic_dial_img_43_148537_7,
	&face_red_magic_dial_img_43_148537_8,
	&face_red_magic_dial_img_43_148537_9,
};
const lv_img_dsc_t *face_red_magic_dial_img_48_151287_group[] = {
	&face_red_magic_dial_img_48_151287_0,
	&face_red_magic_dial_img_48_151287_1,
	&face_red_magic_dial_img_48_151287_2,
	&face_red_magic_dial_img_48_151287_3,
	&face_red_magic_dial_img_48_151287_4,
	&face_red_magic_dial_img_48_151287_5,
	&face_red_magic_dial_img_48_151287_6,
	&face_red_magic_dial_img_48_151287_7,
	&face_red_magic_dial_img_48_151287_8,
	&face_red_magic_dial_img_48_151287_9,
};




#endif

void init_face_red_magic(void (*callback)(const char*, const lv_img_dsc_t *, lv_obj_t **, lv_obj_t **)){
#ifdef ENABLE_FACE_RED_MAGIC
    face_red_magic = lv_obj_create(NULL);
    lv_obj_clear_flag(face_red_magic, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(face_red_magic, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(face_red_magic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(face_red_magic, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(face_red_magic, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(face_red_magic, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(face_red_magic, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(face_red_magic, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_add_event_cb(face_red_magic, onFaceEvent, LV_EVENT_ALL, NULL);

    
    face_red_magic_0_1862 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_0_1862, &face_red_magic_dial_img_0_1862_0);
    lv_obj_set_width(face_red_magic_0_1862, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_0_1862, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_0_1862, 0);
    lv_obj_set_y(face_red_magic_0_1862, 0);
    lv_obj_add_flag(face_red_magic_0_1862, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_0_1862, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_1_1156 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_1_1156, &face_red_magic_dial_img_1_1156_0);
    lv_obj_set_width(face_red_magic_1_1156, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_1_1156, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_1_1156, 290);
    lv_obj_set_y(face_red_magic_1_1156, 111);
    lv_obj_add_flag(face_red_magic_1_1156, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_1_1156, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_2_131494 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_2_131494, &face_red_magic_dial_img_2_131494_0);
    lv_obj_set_width(face_red_magic_2_131494, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_2_131494, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_2_131494, 279);
    lv_obj_set_y(face_red_magic_2_131494, 111);
    lv_obj_add_flag(face_red_magic_2_131494, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_2_131494, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_3_131494 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_3_131494, &face_red_magic_dial_img_2_131494_0);
    lv_obj_set_width(face_red_magic_3_131494, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_3_131494, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_3_131494, 268);
    lv_obj_set_y(face_red_magic_3_131494, 111);
    lv_obj_add_flag(face_red_magic_3_131494, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_3_131494, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_4_131494 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_4_131494, &face_red_magic_dial_img_2_131494_0);
    lv_obj_set_width(face_red_magic_4_131494, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_4_131494, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_4_131494, 257);
    lv_obj_set_y(face_red_magic_4_131494, 111);
    lv_obj_add_flag(face_red_magic_4_131494, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_4_131494, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_5_131494 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_5_131494, &face_red_magic_dial_img_2_131494_0);
    lv_obj_set_width(face_red_magic_5_131494, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_5_131494, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_5_131494, 281);
    lv_obj_set_y(face_red_magic_5_131494, 236);
    lv_obj_add_flag(face_red_magic_5_131494, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_5_131494, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_6_131494 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_6_131494, &face_red_magic_dial_img_2_131494_0);
    lv_obj_set_width(face_red_magic_6_131494, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_6_131494, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_6_131494, 270);
    lv_obj_set_y(face_red_magic_6_131494, 236);
    lv_obj_add_flag(face_red_magic_6_131494, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_6_131494, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_7_131494 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_7_131494, &face_red_magic_dial_img_2_131494_0);
    lv_obj_set_width(face_red_magic_7_131494, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_7_131494, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_7_131494, 259);
    lv_obj_set_y(face_red_magic_7_131494, 236);
    lv_obj_add_flag(face_red_magic_7_131494, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_7_131494, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_8_0 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_8_0, &face_red_magic_dial_img_8_0_0);
    lv_obj_set_width(face_red_magic_8_0, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_8_0, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_8_0, 70);
    lv_obj_set_y(face_red_magic_8_0, 110);
    lv_obj_add_flag(face_red_magic_8_0, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_8_0, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_9_0 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_9_0, &face_red_magic_dial_img_8_0_0);
    lv_obj_set_width(face_red_magic_9_0, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_9_0, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_9_0, 60);
    lv_obj_set_y(face_red_magic_9_0, 110);
    lv_obj_add_flag(face_red_magic_9_0, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_9_0, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_10_138312 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_10_138312, &face_red_magic_dial_img_10_138312_0);
    lv_obj_set_width(face_red_magic_10_138312, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_10_138312, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_10_138312, 70);
    lv_obj_set_y(face_red_magic_10_138312, 103);
    lv_obj_add_flag(face_red_magic_10_138312, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_10_138312, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_11_138312 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_11_138312, &face_red_magic_dial_img_10_138312_0);
    lv_obj_set_width(face_red_magic_11_138312, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_11_138312, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_11_138312, 60);
    lv_obj_set_y(face_red_magic_11_138312, 103);
    lv_obj_add_flag(face_red_magic_11_138312, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_11_138312, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_12_138312 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_12_138312, &face_red_magic_dial_img_10_138312_0);
    lv_obj_set_width(face_red_magic_12_138312, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_12_138312, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_12_138312, 50);
    lv_obj_set_y(face_red_magic_12_138312, 103);
    lv_obj_add_flag(face_red_magic_12_138312, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_12_138312, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_13_133026 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_13_133026, &face_red_magic_dial_img_13_133026_0);
    lv_obj_set_width(face_red_magic_13_133026, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_13_133026, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_13_133026, 81);
    lv_obj_set_y(face_red_magic_13_133026, 103);
    lv_obj_add_flag(face_red_magic_13_133026, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_13_133026, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_14_136230 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_14_136230, &face_red_magic_dial_img_14_136230_0);
    lv_obj_set_width(face_red_magic_14_136230, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_14_136230, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_14_136230, 81);
    lv_obj_set_y(face_red_magic_14_136230, 103);
    lv_obj_add_flag(face_red_magic_14_136230, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_14_136230, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_15_0 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_15_0, &face_red_magic_dial_img_8_0_0);
    lv_obj_set_width(face_red_magic_15_0, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_15_0, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_15_0, 50);
    lv_obj_set_y(face_red_magic_15_0, 110);
    lv_obj_add_flag(face_red_magic_15_0, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_15_0, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_16_138312 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_16_138312, &face_red_magic_dial_img_10_138312_0);
    lv_obj_set_width(face_red_magic_16_138312, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_16_138312, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_16_138312, 238);
    lv_obj_set_y(face_red_magic_16_138312, 78);
    lv_obj_add_flag(face_red_magic_16_138312, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_16_138312, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_17_138312 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_17_138312, &face_red_magic_dial_img_10_138312_0);
    lv_obj_set_width(face_red_magic_17_138312, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_17_138312, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_17_138312, 228);
    lv_obj_set_y(face_red_magic_17_138312, 78);
    lv_obj_add_flag(face_red_magic_17_138312, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_17_138312, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_18_138312 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_18_138312, &face_red_magic_dial_img_10_138312_0);
    lv_obj_set_width(face_red_magic_18_138312, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_18_138312, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_18_138312, 218);
    lv_obj_set_y(face_red_magic_18_138312, 78);
    lv_obj_add_flag(face_red_magic_18_138312, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_18_138312, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_19_138312 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_19_138312, &face_red_magic_dial_img_10_138312_0);
    lv_obj_set_width(face_red_magic_19_138312, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_19_138312, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_19_138312, 208);
    lv_obj_set_y(face_red_magic_19_138312, 78);
    lv_obj_add_flag(face_red_magic_19_138312, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_19_138312, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_21_133464 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_21_133464, &face_red_magic_dial_img_21_133464_0);
    lv_obj_set_width(face_red_magic_21_133464, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_21_133464, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_21_133464, 57);
    lv_obj_set_y(face_red_magic_21_133464, 56);
    lv_obj_add_flag(face_red_magic_21_133464, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_21_133464, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_30_134849 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_30_134849, &face_red_magic_dial_img_30_134849_0);
    lv_obj_set_width(face_red_magic_30_134849, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_30_134849, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_30_134849, 314);
    lv_obj_set_y(face_red_magic_30_134849, 153);
    lv_obj_add_flag(face_red_magic_30_134849, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_30_134849, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_31_134849 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_31_134849, &face_red_magic_dial_img_30_134849_0);
    lv_obj_set_width(face_red_magic_31_134849, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_31_134849, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_31_134849, 304);
    lv_obj_set_y(face_red_magic_31_134849, 153);
    lv_obj_add_flag(face_red_magic_31_134849, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_31_134849, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_32_134849 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_32_134849, &face_red_magic_dial_img_30_134849_0);
    lv_obj_set_width(face_red_magic_32_134849, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_32_134849, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_32_134849, 280);
    lv_obj_set_y(face_red_magic_32_134849, 153);
    lv_obj_add_flag(face_red_magic_32_134849, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_32_134849, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_33_134849 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_33_134849, &face_red_magic_dial_img_30_134849_0);
    lv_obj_set_width(face_red_magic_33_134849, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_33_134849, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_33_134849, 270);
    lv_obj_set_y(face_red_magic_33_134849, 153);
    lv_obj_add_flag(face_red_magic_33_134849, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_33_134849, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_34_139822 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_34_139822, &face_red_magic_dial_img_34_139822_0);
    lv_obj_set_width(face_red_magic_34_139822, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_34_139822, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_34_139822, 294);
    lv_obj_set_y(face_red_magic_34_139822, 158);
    lv_obj_add_flag(face_red_magic_34_139822, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_34_139822, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_43_148537 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_43_148537, &face_red_magic_dial_img_43_148537_0);
    lv_obj_set_width(face_red_magic_43_148537, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_43_148537, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_43_148537, 251);
    lv_obj_set_y(face_red_magic_43_148537, 271);
    lv_obj_add_flag(face_red_magic_43_148537, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_43_148537, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_44_148537 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_44_148537, &face_red_magic_dial_img_43_148537_0);
    lv_obj_set_width(face_red_magic_44_148537, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_44_148537, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_44_148537, 241);
    lv_obj_set_y(face_red_magic_44_148537, 271);
    lv_obj_add_flag(face_red_magic_44_148537, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_44_148537, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_45_148537 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_45_148537, &face_red_magic_dial_img_43_148537_0);
    lv_obj_set_width(face_red_magic_45_148537, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_45_148537, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_45_148537, 231);
    lv_obj_set_y(face_red_magic_45_148537, 271);
    lv_obj_add_flag(face_red_magic_45_148537, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_45_148537, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_46_148537 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_46_148537, &face_red_magic_dial_img_43_148537_0);
    lv_obj_set_width(face_red_magic_46_148537, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_46_148537, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_46_148537, 221);
    lv_obj_set_y(face_red_magic_46_148537, 271);
    lv_obj_add_flag(face_red_magic_46_148537, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_46_148537, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_47_148537 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_47_148537, &face_red_magic_dial_img_43_148537_0);
    lv_obj_set_width(face_red_magic_47_148537, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_47_148537, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_47_148537, 211);
    lv_obj_set_y(face_red_magic_47_148537, 271);
    lv_obj_add_flag(face_red_magic_47_148537, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_47_148537, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_48_151287 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_48_151287, &face_red_magic_dial_img_48_151287_0);
    lv_obj_set_width(face_red_magic_48_151287, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_48_151287, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_48_151287, 272);
    lv_obj_set_y(face_red_magic_48_151287, 172);
    lv_obj_add_flag(face_red_magic_48_151287, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_48_151287, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_49_151287 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_49_151287, &face_red_magic_dial_img_48_151287_0);
    lv_obj_set_width(face_red_magic_49_151287, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_49_151287, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_49_151287, 251);
    lv_obj_set_y(face_red_magic_49_151287, 172);
    lv_obj_add_flag(face_red_magic_49_151287, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_49_151287, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_50_151287 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_50_151287, &face_red_magic_dial_img_48_151287_0);
    lv_obj_set_width(face_red_magic_50_151287, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_50_151287, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_50_151287, 324);
    lv_obj_set_y(face_red_magic_50_151287, 172);
    lv_obj_add_flag(face_red_magic_50_151287, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_50_151287, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_51_151287 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_51_151287, &face_red_magic_dial_img_48_151287_0);
    lv_obj_set_width(face_red_magic_51_151287, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_51_151287, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_51_151287, 303);
    lv_obj_set_y(face_red_magic_51_151287, 172);
    lv_obj_add_flag(face_red_magic_51_151287, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_51_151287, LV_OBJ_FLAG_SCROLLABLE );

    face_red_magic_52_136123 = lv_img_create(face_red_magic);
    lv_img_set_src(face_red_magic_52_136123, &face_red_magic_dial_img_52_136123_0);
    lv_obj_set_width(face_red_magic_52_136123, LV_SIZE_CONTENT);
    lv_obj_set_height(face_red_magic_52_136123, LV_SIZE_CONTENT);
    lv_obj_set_x(face_red_magic_52_136123, 292);
    lv_obj_set_y(face_red_magic_52_136123, 179);
    lv_obj_add_flag(face_red_magic_52_136123, LV_OBJ_FLAG_ADV_HITTEST );
    lv_obj_clear_flag(face_red_magic_52_136123, LV_OBJ_FLAG_SCROLLABLE );


    callback("red magic", &face_red_magic_dial_img_preview_0, &face_red_magic, NULL);

#endif
}

void update_time_red_magic(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday)
{
#ifdef ENABLE_FACE_RED_MAGIC
    if (!face_red_magic)
    {
        return;
    }
	lv_img_set_src(face_red_magic_30_134849, face_red_magic_dial_img_30_134849_group[(month / 1) % 10]);
	lv_img_set_src(face_red_magic_31_134849, face_red_magic_dial_img_30_134849_group[(month / 10) % 10]);
	lv_img_set_src(face_red_magic_32_134849, face_red_magic_dial_img_30_134849_group[(day / 1) % 10]);
	lv_img_set_src(face_red_magic_33_134849, face_red_magic_dial_img_30_134849_group[(day / 10) % 10]);
	lv_img_set_src(face_red_magic_48_151287, face_red_magic_dial_img_48_151287_group[(hour / 1) % 10]);
	lv_img_set_src(face_red_magic_49_151287, face_red_magic_dial_img_48_151287_group[(hour / 10) % 10]);
	lv_img_set_src(face_red_magic_50_151287, face_red_magic_dial_img_48_151287_group[(minute / 1) % 10]);
	lv_img_set_src(face_red_magic_51_151287, face_red_magic_dial_img_48_151287_group[(minute / 10) % 10]);

#endif
}

void update_weather_red_magic(int temp, int icon)
{
#ifdef ENABLE_FACE_RED_MAGIC
    if (!face_red_magic)
    {
        return;
    }
	lv_img_set_src(face_red_magic_21_133464, face_red_magic_dial_img_weather[icon % 8]);

#endif
}

void update_status_red_magic(int battery, bool connection){
#ifdef ENABLE_FACE_RED_MAGIC
    if (!face_red_magic)
    {
        return;
    }
	lv_img_set_src(face_red_magic_2_131494, face_red_magic_dial_img_2_131494_group[(battery / 1) % 10]);
	lv_img_set_src(face_red_magic_3_131494, face_red_magic_dial_img_2_131494_group[(battery / 10) % 10]);
	lv_img_set_src(face_red_magic_4_131494, face_red_magic_dial_img_2_131494_group[(battery / 100) % 10]);
	if (battery < 100)
	{
		lv_obj_add_flag(face_red_magic_4_131494, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_clear_flag(face_red_magic_4_131494, LV_OBJ_FLAG_HIDDEN);
	}

#endif
}

void update_activity_red_magic(int steps, int distance, int kcal)
{
#ifdef ENABLE_FACE_RED_MAGIC
    if (!face_red_magic)
    {
        return;
    }
	lv_img_set_src(face_red_magic_16_138312, face_red_magic_dial_img_10_138312_group[(kcal / 1) % 10]);
	lv_img_set_src(face_red_magic_17_138312, face_red_magic_dial_img_10_138312_group[(kcal / 10) % 10]);
	lv_img_set_src(face_red_magic_18_138312, face_red_magic_dial_img_10_138312_group[(kcal / 100) % 10]);
	lv_img_set_src(face_red_magic_19_138312, face_red_magic_dial_img_10_138312_group[(kcal / 1000) % 10]);
	lv_img_set_src(face_red_magic_43_148537, face_red_magic_dial_img_43_148537_group[(steps / 1) % 10]);
	lv_img_set_src(face_red_magic_44_148537, face_red_magic_dial_img_43_148537_group[(steps / 10) % 10]);
	lv_img_set_src(face_red_magic_45_148537, face_red_magic_dial_img_43_148537_group[(steps / 100) % 10]);
	lv_img_set_src(face_red_magic_46_148537, face_red_magic_dial_img_43_148537_group[(steps / 1000) % 10]);
	lv_img_set_src(face_red_magic_47_148537, face_red_magic_dial_img_43_148537_group[(steps / 10000) % 10]);

#endif
}

void update_health_red_magic(int bpm, int oxygen)
{
#ifdef ENABLE_FACE_RED_MAGIC
    if (!face_red_magic)
    {
        return;
    }
	lv_img_set_src(face_red_magic_5_131494, face_red_magic_dial_img_2_131494_group[(bpm / 1) % 10]);
	lv_img_set_src(face_red_magic_6_131494, face_red_magic_dial_img_2_131494_group[(bpm / 10) % 10]);
	lv_img_set_src(face_red_magic_7_131494, face_red_magic_dial_img_2_131494_group[(bpm / 100) % 10]);

#endif
}

void update_all_red_magic(int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_RED_MAGIC
    update_time_red_magic(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_red_magic(temp, icon);
    update_status_red_magic(battery, connection);
    update_activity_red_magic(steps, distance, kcal);
    update_health_red_magic(bpm, oxygen);
#endif
}

void update_check_red_magic(lv_obj_t *root, int second, int minute, int hour, bool mode, bool am, int day, int month, int year, int weekday, 
    int temp, int icon, int battery, bool connection, int steps, int distance, int kcal, int bpm, int oxygen)
{
#ifdef ENABLE_FACE_RED_MAGIC
    if (root != face_red_magic)
    {
        return;
    }
    update_time_red_magic(second, minute, hour, mode, am, day, month, year, weekday);
    update_weather_red_magic(temp, icon);
    update_status_red_magic(battery, connection);
    update_activity_red_magic(steps, distance, kcal);
    update_health_red_magic(bpm, oxygen);
#endif
}


