
// File generated by bin2lvgl
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: RED_MAGIC_410

#include "../red_magic_410.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif


// LVGL 9 format (RGB565) // LVGL_9 compatible

const LV_ATTRIBUTE_MEM_ALIGN uint8_t face_red_magic_410_dial_img_34_139822_data_0[] = {
	//RGB565 data with alpha
	0x6D,0x6B,0x50,0x84,0x71,0x8C,0x71,0x8C,0x71,0x8C,0x51,0x8C,0xEF,0x7B,0xAA,0x52,0x4C,0x63,0x6D,0x6B,
	0x6D,0x6B,0x6D,0x6B,0x6D,0x6B,0x2C,0x63,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,
	0xFF,0xFF,
};

const lv_img_dsc_t face_red_magic_410_dial_img_34_139822_0 = {
    .header.magic = LV_IMAGE_HEADER_MAGIC,
    .header.w = 7,
    .header.h = 2,
    .data_size = sizeof(face_red_magic_410_dial_img_34_139822_data_0),
    .header.cf = LV_COLOR_FORMAT_NATIVE_WITH_ALPHA,
    .data = face_red_magic_410_dial_img_34_139822_data_0};
